version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: stock_management_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_agent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: stock_management_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - stock_network

networks:
  stock_network:
    driver: bridge

volumes:
  postgres_data:
